### ISSUE TITLE
Create a 1.0 Milestone

### ISSUE THREAD

**Issue by Plecra** [overdrivenpotato/rust-psp#46]
It's nice to make the aims of the project clear to users and contributors alike. A milestone will be able to keep track of the progress made on the features in the Roadmap in a clear and concise way.

This also creates a chance to pool the relevant information for each feature and write up mentoring instructions to get the ball rolling.

- [ ] User mode support (Was this #41?)
- [ ] Kernel mode support
- [ ] `libc` shim
- [ ] `std` support
- [ ] Complete `EBOOT.PBP` generation
  - [ ] Signing
- [ ] *Cleaning everything up*
- [ ] Tests
  - [ ] A remote debugger? 🥺 

I'd also like to suggest keeping a knowledge base (maybe a Book) of what is known about the PSP. `prx.md` already contains the beginnings of this, and I think it'd be good to lay things out for future maintainers. I'd be happy to compile what we have at the moment if you can point me to what's been used in the implementation so far.

**Comment by overdrivenpotato** [comment]
Good idea, I'll create a v1.0 milestone.

As for the book, there is this existing comprehensive resource: http://hitmen.c02.at/files/yapspd/psp_doc/frames.html It's missing some things, but unfortunately I don't have time to put into documenting the PSP formats further. It was the main resource used behind this project. If somebody creates a new comprehensive PSP documentation book, I can link it in the README.

**Comment by overdrivenpotato** [comment]
Closing this as we now have a v1.0.0 milestone.
