### ISSUE TITLE
Reverse Engineering Checklist

### ISSUE THREAD

**Issue by sajattack** [overdrivenpotato/rust-psp#56]
- [x] sceGuDebugPrint - Puzzle Bobble
- [ ] sceGim - Image Loading - Puzzle Bobble
- [ ] sceWave - Audio Loading - Puzzle Bobble
- [ ] sceSas - Seems like a software implementation of a basic synth -  Yu-Gi-Oh
- [ ] sceVfpu - Vfpu intrinsics -  Yu-Gi-Oh
- [ ] sceCcc - Character conversion (utf8 et-al) - Yu-Gi-Oh
- [ ] sceFpu - Fpu math - Yu-Gi-Oh

**Comment by sajattack** [comment]
These are in no particular order. I think sceVfpu should be top priority.

**Comment by sajattack** [comment]
Not reverse engineering because it's in PPSSPP already but since we're tracking libs not in pspsdk here, scePsmfPlayer is NID based video player type thing it seems.

**Comment by sajattack** [comment]
sceLibFont is also available in PPSSPP

**Comment by sajattack** [comment]
Jan Sangoku Musou has a bunch of empty functions with strange names like sceVif, sceGs, sceCd, scePad, sceDbc. Stubs or something but I don't see where they're coming from because there's nothing unusual in rodata.sceResident

**Comment by sajattack** [comment]
Working theory is the Jan Sangoku Musou stuff was compiled for both PS2 and PSP, those are PS2 function names.

**Comment by sajattack** [comment]
It looks like sceCcc later became nid based like scePsmf did.

**Comment by sajattack** [comment]
Star Driver only has debug strings, not full debug symbols.

**Comment by albe** [comment]
http://web.archive.org/web/20120731071802/http://forums.ps2dev.org/viewtopic.php?t=6929

Dropping this here in the hope it might be of value. I'm the Raphael guy from that thread.

**Comment by sajattack** [comment]
Thanks!

**Comment by dvdkon** [comment]
There's a leaked official Sony SDK on Archive.org that has headers and documentation for all of these. My understanding is that writing Rust function/struct definitions based on these isn't a copyright violation, but I understand if you want to be more cautious.

It's a lot of functions, so if I ever get around to writing something for the PSP that needs these I'll add just the ones I need.
